---
title: Getting started
format: 
    pdf: default
    ipynb: default
jupyter: python3
execute: 
    echo: true
    eval: false
---

## Learning goals  
- Install `git` and clone the course repository from `github`
- Install an Integrated Development Environment (IDE), if needed
- Learn about text and cells in a jupyter notebook

## git and github
These course notes are organized using the version control system `git`. If this does not mean anything to you, don't mind. At the moment, this only means that you need to [install `git`](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git) on your system, and run in the folder where you want to have the course notes
```
git clone https://github.com/pfaffelh/python_for_data/
```
With this command, you are _cloning_ the repository of the course notes from github. You can also look at this repository [online](https://github.com/pfaffelh/python_for_data/). 

There is a good chance that the course notes will be updated during the upcoming weeks. In order to obtain the most current version, you need to run
```
git pull
```
There is (at least) one catch for using `git`: If you are changing one of the course files locally on your system, but the file has updated, `git pull` realizes the different versions and rejects to do `git pull`. The best way out is to do all changes to the files in the folder `myFiles`, or only change the files `...ipynb`. All these files are excluded from any update with `git pull`. 

## Your python environment
We will assume that python is installed on your system. These course notes are written with python 3.13, but other versions might work as well. In addition to plan `python`, we will need some libraries. Which ones we need (including their versions) is written in the file `requirements.txt` in the main folder of these notes. We recomment that you do the following: 

1. Create a virtual environment using `python -m venv venv` or `python3 -m venv venv`. 
2. Activate this environment by `source venv/bin/activate`,
3. Install the libraries using `pip3 install -r requirements.txt` (or `pip install -r requirements.txt`).

General note: We avoid repeating the distinction between the commands `python` and `python3`, and will simply write `python3` in the sequel.

## Starting a Jupyter notebook

There are basically three ways `python` commands can be run: 

1. In interactive mode on the command line by typing `python3` in your shell,
2. In `python`-scripts, usually ending with `myScript.py`. You can run these using `python3 myScript.py`.
3. Jupyter notebooks have the opportunity to mix usual text with `python` commands. We will use these in this course. 

For Jupyter notebooks, there are basically two ways to run them: 

1. Start the Jupyter server using `jupyter lab` (hopefully, it is already installed), which opens your browser where you can edit and save what you have done;
2. Use `vscode` as you IDE and work from there; see below.

## vscode
When programming, we need to type code. This is possible in a code editor, and best done in a more sophisticated environment such as [`vscode`](https://code.visualstudio.com/). It is best to acticvate your vertual environment using `source venv/bin/activate` before starting vscode. In order to start vscode, go to the main folder of the course notes, and type `code .` vscode can be used for all three ways to write Python commands: 

1. Use `Terminal -> New Terminal` in order to open a terminal, type `python3` and you are in interactive mode,
2. Write a Python script and run it using the opoened terminal,
3. Click on some Jupyther notebook, and vscode starts the Jupyter server for you. 

## A first Python cell
Here is the first cell of Python-code:

```{python}
x = "Hello, "
y = "world"
z = "!"
print(x+y+z)
```
In order to execute this code, press the play bottom on the left (or hit `Control + Enter` within the Python-cell).

## Using AI (ChatGPT, Gemini etc)
During the last years, AI has increasingly improved in code writing. You are encouraged to use this new technology! As usual when learning new things, this new tool can help a lot, and will be able to solve the exercises within the Jupyter notebooks. However, you still have to undestand the code, and what might go wrong during execution. As a first course in Python, you will end up having up to a few hundred lines of code, which has to be coherent. You must know the structure of that code, and in order to extend it, fix bugs etc. If you are ever involved in bigger projects, this is even more important. 

## Overview of the course

Basically, the course has three parts: 

1. Python basics: data types, functions, loops, conditions etc; (Lessons 01, 02, 03, 04)
2. Tools for data analysis: numpy, matplotlib, pandas; (Lessons 05, 05, 07, 08)
3: Project: choose data that interests you and creat a dashboard


