---
title: Simple Data types
format: 
    pdf: default
    ipynb: default
jupyter: python3
---

[Download notebook](notebooks/02_simple_data_types.ipynb).

## Overview

Every variable or other object in python has a type. This is the kind of information which is stored insice the variable or object Here is an overview over the most important simple data types. 


| Type       | Example   | Description              |
|------------|-----------|--------------------------|
| `int`      | `5`       | Integer                  |
| `float`    | `3.14`    | Floating-point number    |
| `bool`     | `True`    | Boolean value            |
| `str`      | `"hello"` | Text string              |
| `NoneType` | `None`    | No value / null value    |

- You can find about the type of any expression `x` in Python using `type(x)`. 
- In fact, `type(x)` is already the first example of a built-in-function. The function `type` takes a single value as input, and returns its type. We will encounter various more functions already in this section. We will learn more about functions (built-in and self-written) in  @sec-functions.
- There are conversions between some types. For example, `"0"` is a string, but `int("0")` (again a function, taking a single value, and returning its integer value) the integer `0`. Conversely, `str(0)` is the string `"0"`. We will have more examples below. 

## int

With `int`s (numbers ...,-2,-1,0,1,2,... ), you can compute as usual. 

```{python}
x = 7
y = 2
print("x + y = ", x + y)
print("x * y =  ", x * y)
```
```{python}
# x to the power of y
print("x ** y = ", x ** y)
```
```{python}
# x divided by y (which gives a `float`)
print("x / y = ", x / y)
```
```{python}
# integer-valued division of x by y 
print("x // y = ", x // y)
```
```{python}
# x modulo y
print("x % y = ", x % y)
```

In most programming languages (e.g. `C++`), there is a minimal and a maximal possible value for an int. Python, however, does not have this limitation. Only the amount of available memory restricts the numbers which can be stored in an `int`.


## float

Generally speaking, floats are decimal numbers, which come with an exponent and a mantissa, e.g. $1.2 \cdot 10^2$. Python can do the same computations as with ints, but the following should be kept in mind:

- If you type `1`, Python thinks this is an int, but if you type `1.0` or `1.`, Python thinks this is a float. 
- Unlike ints, floats do have a maximal and minimal element. The reason is that every float is stored in 64 bits, one for the sign, 11 for the exponent and 52 for the mantissa. As a result, floats range from about $10^{-324}$ to $10^{308}$. 
- When doing mixed computations with floats and int, e.g. `1.0 + 1`, the int is changed into a float. 
- It is not possible to perform exact computations with some floats; see the example below.

```{python}
x = 1.0
y = 1
print("x + y = ", x + y)
```
```{python}
print("0.1 + 0.2 = ", 0.1 + 0.2)
```

Special floats are `inf`, `-inf` and `nan` (not a number). Let us see them in action:

```{python}
print((10. ** 308) * 10)
```
```{python}
print((10 ** 308) * 10)
```
```{python}
print((10 ** (-323)) / 10)
```
```{python}
print((10. ** 308) * 10 - (10. ** 308) * 10)
```

You can transform ints to floats and vice versa by using `float()` and `int()`.
```{python}
print(float(0))
```
```{python}
print(int(0.0))
```
```{python}
print(int(0.5))
```

If you deliberately want to introduce `nan` or `inf`, you can do this: 
```{python}
print(float("inf"))
print(float("nan"))
```

On `float`, you can use many functions. We only name two at the moment, for some float `x`:

* `abs(x)`: The absolute value of `x`.
* `round(x)` and `round(x,n)`: Round `x` to the next `int`, or after `n` digits.

In @sec-math, we will encounter that many more usual functions (like `sqrt`) can be used on floats, but we need to `import` the mathematical library for this. 

## bool

There are exactly two boolean values, known as `True` and `False`. You can compute with them using `not`, `and`, `or` and 'xor'. In addition, `True` and `False` can be the result of a condition, such as the expression `1 == 2`. 

```{python}
x = True
y = False
print("not x =", not x)
```
```{python}
print("x and y =", x and y)
```
```{python}
print("x or y =", x or y)
```
```{python}
print("x xor y =", x ^ y)
```
```{python}
print("((not x) == y) =", (not x) == y)
```
```{python}
print("(1 == 2) =", 1 == 2)
```
```{python}
# Python converts `bool` into `int`
print("x + y =", x + y)
```
```{python}
# != means "not equal"
print("(1 != 2) =", 1 != 2)
```
```{python}
# < refers to less than
print("(1 < 1) =", 1 < 1)
```
```{python}
# <= refers to less than or equal
print("(1 <= 1) =", 1 <= 1)
```
```{python}
z = float("nan")
print("(z == z) =", z == z)
```

## string

In many cases, strings are objects in quotation markes, such as in `"Hello, world!". 

- **Operations on strings**: You can concencatenate strings using `+` as in `"Python " + "for " + "Data " + "Analysis" (but you cannot subtract strings). You can also repeat a string by multiplying it with an int. 
- **f-strings**: They were introduced in Python 3.6. They are the way to go if you want to mix description and variables. They are written as `f"Hello, {name}"`. The `f` introduces the f-string. Within curly braces, there is a variable, which should be printed instead of the variable name. 
- **Special characters**: There are many of them, we only mention `\t` (tabulator) and `\n` (new line) here. 
- **Multiline strings**: Usually, python interprets a new line such that all commands are finished. However, if you want to use a sttring spanning multiple lines, you don't want this. Multiline strings start and end with `"""` (a triple quotation mark). 
- **Quotation marks**: In various cases, you can use `'` instead of `"`. Sometimes this is useful when nesting quotation marks. 
- **Substrings**: We will learn more about substrings, but here is already a way to see if a substring occurs within a string or not. The value of `"th" in "Python"` amount to `True`. 


```{python}
x = "Hello," 
y = "world"
# Concatenating two (or more) strings
print(x + y + "!")
```
```{python}
# repeating a string 
z = "bla"
print(z*3)
```
```{python}
# a special character
print("\U0001F60E")
```
```{python}
# an example of an f-string
name = "Alice"
print(f"Hello {name} 😀")
```
```{python}
# a multiline string
text = """This is a multiline string.
It can span several lines.
Each line break is preserved."""
print(text)
```
```{python}
# determine if a given substring occurs within a string
print("Is 'th' a substring of 'Python'? ", 'th' in 'Python')
print("Is 'the' a substring of 'Python'? ", 'the' in 'Python')
```

For strings, there are various build-in functions. We mention some of them. Here, `s` is a string. 

* `str.strip(s)`: Deletes spaces in the front and back. 
* `len(s)`: gives the length of the string. 
* `str.replace(s, "x", "y")`: Replaces each occurrence of `"x"` in `s` by `"y"`.
* `str.split(s, "x")`: Splits `s` at each occurrence of `"x". The result is a `list`, which we will encounter in @sec-list.
", ".join
* `str.lower(s)`: Return the same string, but all letters are lowercase. 
* `str.upper(s)`: Return the same string, but all letters are uppercase. 
* `str.isalpha(s)`: 
* `str.isdigit(s)`: Returns `True` if the string is actually a number, and `False` otherwise.
* `str.isalnum(s)`: Returns `True` if the string consists only of letters and numbers, and `False` otherwise.
* `str.isspace(s)`: Returns `True` if the string consists only empty spaces, and `False` otherwise.
* `str.islower(s)`: Returns `True` if the string consists only of lower case letters, and `False` otherwise.
* `str.isupper(s)`: Returns `True` if the string consists only of upper case letters, and `False` otherwise.
* `str.count(s, "x")`: Counts how ofter `"x"` appears in `s`. 

Here is another very useful notation convention, known as dot-notation: For a function `str.something(s,...)`, where `s` is of type `str`, you can as well write `s.something()`. For example, `s.strip()` is the same as `str.strip(s)`. 


## NoneType

When analysing data, it is common to have missing values. These usually come as `None`. This is different from anything else we encountered so far (including `nan` and `False`).

```{python}
x = None
print(x)
```
```{python}
print("(x is None) =", x is None)
```
```{python}
print("(None == False) =", None == False)
```
```{python}
print("(None == nan) =", None == float("nan"))
```

## Exercises 

**Exercise 1:**
Find out how to use scientific notation in Python. (If you don't know what this is, please find out!)

**Exercise 2:**
Is there a Python package which can compute `0.1 + 0.2 == 0.3` without error?

**Exercise 3:**
Print `"Hello, world!"` including the quotation marks in the output.

**Exercise 4:**
Do newlines and tabs `\n`, `\t` count in `str.isspacce()`? How do numbers interact with `str.islower()`? If `s` is the strign of a number, what is `s.lower()`? Play around a bit with these fucntions and edge cases you might see in data. 

**Exercise 5:**
If you are on Windows, it is annoying that file paths come with `\`, which is interpreted as the start of a special character. Find out two ways how to give the string of the file path `C:\Users\Alice\Documents\file.txt`.

**Exercise 6:**
What is `bool(None)`? What is `int(None)`?

**Exercise 7:**
In tables, we often have `""` for a missing value. Is this the same as `None`?


