---
title: 2 Control flow -- conditions, loops, and functions
format: 
    pdf: default
    ipynb: default
jupyter: python3
---

Coding starts to become interesting when we can control how variables change, and repeat operations. 

## If elif else
As a simple (mathematical) example, let us compute the minimum of two numbers., which works by an `if`-condition:
```{python3}
a = 2
b = 5
if a < b:
    res = a
else:
    res = b
print(f"The minimum of {a} and {b} is:", res)
```
In general, the structure of an `if`-statement reads:
```
if _condition1_:
    case1
elif _condition2_:
    case2
elif _condition3_:
    case3
...
else:
    case_else
```
Here, read `elif` alse `else if`, which means that the code jumps into this case if the respective condition is the first to hold. The `else` case only applied if both the `if` and all `elif` conditions do not apply. 

In fact, there are abbreviations in python3 which are very handy. In particular, look at this piece of code.
```{python3}
res = a if a < b else b
print(f"The minimum of {a} and {b} is:", res)
```

Let us make another example, also using `elif`. Given some `n`, the task is to print `Fizz` if `n` is a multiple of 3, `Buzz`, if it is a multiple of 5, and `FizzBuzz` if both conditions are satisfied.
```{python3}
n = 165
res = ""
if n % 3 == 0 and n % 5 == 0:
    res = "FizzBuzz"
elif n % 3 == 0:
    res = "Fizz"
elif n % 5 == 0:
    res = "Buzz"
print(res)
```

Exercise 

Can you code the `FizzBuzz` example in a single line of code? (So, dependent on some `n`, give one line of code, which gives `Fizz` if `n` is a multiple of 3, `Buzz`, if it is a multiple of 5, and `FizzBuzz` if both conditions are satisfied.

Exercise 

Multiple `elif`s in a row are not very elegant. Python3 (since version 3.10) comes with `match`. Find out how you can change the `FizzBuzz` example of the main text by using `match` instead of `elif`s.  

## for

There are `for`-loops in Python3, as discussed in this section, and `while`-loops in the next section. The basic use-case of a  `for`-loop is repeating a task several times. As a simple example, adding `b` a number of `a` times, results in `a * b`.

```{python3}
a = 3
b = 7
res = 0
for i in range(a):
    res = res + b
print(f"{a} * {b} = {res}")
```

Importantly, `range(a)` is a synonym for the numbers `0,..., a-1`. (In particular, note that Python3 usually starts counting at `0` and not at `1`, which will also be important in the next chapter.)

The general structure of a `for`-loop is as follows:
```
for _var_ in _iterable:
    _sequence of instructions_
```

Let us look at a more interesting example, computing the greatest common divisor of two numbers, `a` and `b`. A very simple algorithm is going through all numbers `1,...,` in order, and update result each time we encounter a number which divides both, `a` and `b`. (Here, `range(1,a+1)` is a synoym for the numbers `1,...,a`.)

```{python3}
# Basic algorithm for finding the greatest common divisor (gcd) of two numbers
a = 105
b = 33

res = 1
for i in range(1,a+1):
    if a % i == 0 and b % i == 0:
        res = i
print(f"The gcd of {a} and {b} is {res}.")
```
Note, in particular, that the instructios within the `for`-loop depend on `i`.

## while


```{python3}
# Basic algorithm for finding the greatest common divisor (gcd) of two numbers
a = 105
b = 33

res = 1
for i in range(1,a+1):
    if a % i == 0 and b % i == 0:
        res = i
print(f"The gcd of {a} and {b} is {res}.")
```








def gcd(a, b):
    a, b = abs(a), abs(b)

    while b != 0:
        r = a % b
        print(f"a = {a}, b = {b}, remainder = {r}")

        a = b
        b = r

    return a


print("gcd =", gcd(252, 105))

